"""Export Pydantic JSON Schema and TypeScript without importing the app/DB.

Run from backend: python scripts/export_stage1_contracts.py [--check]
The deliberately small JSON Schema renderer fails on unknown schema shapes.
"""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "backend"))
from app.domain.stage1 import FoundationContracts
from app.domain.site_workspace import WorkspaceContracts
from app.domain.assistant_runtime import RuntimeContracts
from app.domain.composition import CompositionContracts


def render(schema):
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return json.dumps(schema["const"])
    if "enum" in schema:
        return " | ".join(json.dumps(x) for x in schema["enum"])
    for union in ("anyOf", "oneOf"):
        if union in schema:
            return "(" + " | ".join(render(x) for x in schema[union]) + ")"
    kind = schema.get("type")
    if kind == "object":
        required = schema.get("required", [])
        return "{\n" + "\n".join(f'  {json.dumps(k)}{"" if k in required else "?"}: {render(v)};' for k, v in schema.get("properties", {}).items()) + "\n}"
    if kind == "array":
        if "prefixItems" in schema:
            return "[" + ", ".join(render(x) for x in schema["prefixItems"]) + "]"
        return f"Array<{render(schema['items'])}>"
    if kind in {"number", "integer"}:
        return "number"
    if kind in {"string", "boolean", "null"}:
        return kind
    raise ValueError(f"Unhandled schema shape: {schema}")


def outputs():
    class AllContracts(FoundationContracts):
        workspace: WorkspaceContracts
        runtime: RuntimeContracts
        composition: CompositionContracts
    schema = AllContracts.model_json_schema(by_alias=True)
    ts = "// GENERATED by backend/scripts/export_stage1_contracts.py. Do not edit.\n"
    for name, definition in schema.pop("$defs").items():
        ts += f"export type {name} = {render(definition)};\n\n"
    ts += f"export type FoundationContracts = {render(schema)};\n"
    return {
        ROOT / "frontend/lib/generated/stage1.ts": ts,
        ROOT / "docs/contracts/stage1.schema.json": json.dumps(AllContracts.model_json_schema(by_alias=True), indent=2) + "\n",
    }


if __name__ == "__main__":
    for path, content in outputs().items():
        if "--check" in sys.argv:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                raise SystemExit(f"Generated contract is stale: {path.name}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    print("Stage 1 contracts verified" if "--check" in sys.argv else "Stage 1 contracts exported")
