import { expect, test } from "@playwright/test";

const projectId = process.env.AI3D_ACCEPTANCE_PROJECT_ID;
test.skip(!projectId, "Requires create_ai3d_workspace_fixture.py; no provider calls");
test("generic mixed design preserves Building and uses normal workspace tools", async ({ page }) => {
  await page.setViewportSize({ width: 1626, height: 982 });
  await page.goto(`/projects/${projectId}/workspace`);
  await expect(page.getByLabel("Search scene components")).toBeVisible({ timeout: 60000 });
  await page.getByRole("tab", { name: "Assistant", exact: true }).click();
  await page.getByRole("button", { name: "Review proposal", exact: true }).click();
  await expect(page.getByLabel("Generic 3D design summary")).toContainText("WAREHOUSE");
  await expect(page.getByLabel("Generic 3D design summary")).toContainText("WATER TANK");
  await page.getByRole("checkbox", { name: "I reviewed the assumptions, warnings and conceptual scope." }).check();
  await page.getByRole("button", { name: "Approve proposal", exact: true }).click();
  const built = page.waitForResponse(response => /\/build$/.test(response.url()) && response.request().method() === "POST");
  await page.getByRole("button", { name: "Approve & Generate 3D", exact: true }).click();
  const response = await built;
  expect(response.ok(), await response.text()).toBeTruthy();
  await expect(page.getByLabel("Proposal review").getByRole("status")).toContainText("Generic 3D concept saved as revision");
  await page.reload();
  const select = async (name: string) => {
    await page.getByRole("tab", { name: "Layers", exact: true }).click();
    await page.getByLabel("Search scene components").fill(name);
    await page.getByRole("button", { name, exact: true }).click();
    await page.getByRole("tab", { name: "Inspect", exact: true }).click();
  };
  await select("c0-0");
  await expect(page.getByLabel("Component identity")).toContainText("office-01");
  await expect(page.getByLabel("Position · metres East", { exact: true })).toHaveValue("5");
  await select("water-tank");
  await expect(page.getByLabel("Component identity")).toContainText("CYLINDER");
  await expect(page.getByLabel("Component identity")).toContainText("design-01");
  await select("parking-pad");
  await expect(page.getByLabel("Component identity")).toContainText("BOX");
  await page.getByRole("button", { name: "Frame selection", exact: true }).click();
  await expect(page.locator(".cesium-widget canvas")).toBeVisible();
  const east = page.getByLabel("Position · metres East", { exact: true });
  await east.fill("15.5"); await east.press("Tab");
  const saved = page.waitForResponse(r => /model-revisions$/.test(r.url()) && r.request().method() === "POST");
  await page.getByRole("button", { name: "Save 3D model revision", exact: true }).click();
  const saveResponse = await saved;
  expect(saveResponse.ok(), await saveResponse.text()).toBeTruthy();
  await page.reload(); await select("parking-pad");
  await expect(east).toHaveValue("15.5");
  await expect(page.getByLabel("Component identity")).toContainText("design-01");
  await page.getByRole("tab", { name: "History", exact: true }).click();
  await page.getByRole("button", { name: "Compare", exact: true }).click();
  await expect(page.getByText("0 added · 0 removed · 1 modified", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Close compare", exact: true }).click();
  await page.getByRole("tab", { name: "Layers", exact: true }).click();
  await page.getByLabel("Search scene components").fill("");
  await page.getByRole("button", { name: "Hide pipe layer", exact: true }).click();
  await expect(page.getByRole("button", { name: "Show pipe layer", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Show pipe layer", exact: true }).click();
  await page.getByRole("tabpanel", { name: "Layers", exact: true }).getByText("Actions", { exact: true }).click();
  await page.getByRole("button", { name: "Select matching", exact: true }).click();
  await page.getByRole("tab", { name: "Inspect", exact: true }).click();
  await page.getByRole("button", { name: "Engineering dock", exact: true }).click();
  await page.getByRole("tab", { name: "SECTION", exact: true }).click();
  await page.getByRole("checkbox", { name: "Underground view", exact: true }).check();
  await page.getByRole("button", { name: "Engineering dock", exact: true }).click();
  await page.getByRole("button", { name: "Frame selection", exact: true }).click();
  // Existing camera flight takes 0.9 seconds; capture its settled reference-plane view.
  await page.waitForTimeout(1800);
  await expect(page.locator(".cesium-widget-errorPanel")).toHaveCount(0);
  await page.screenshot({ path: "test-results/ai3d-workspace-accepted.png" });
});
