import { test, expect } from "@playwright/test";
const projectId = process.env.BUILDING_PATCH_PROJECT_ID;
test.skip(!projectId, "Seed a fresh backend/scripts/create_building_patch_fixture.py project first");
test("review, approve and apply a grounded Building patch through the real workspace", async ({ page }) => {
  await page.setViewportSize({ width: 1626, height: 982 });
  await page.goto(`/projects/${projectId}/workspace`);
  await expect(page.getByLabel("Search scene components")).toBeVisible({ timeout: 60000 });
  await page.getByLabel("Search scene components").fill("c0-0");
  await page.getByRole("button", { name: "c0-0", exact: true }).click();
  await page.getByRole("tab", { name: "Inspect", exact: true }).click();
  const east = page.getByLabel("Position · metres East", { exact: true });
  await expect(east).toHaveValue("5");
  await page.getByRole("tab", { name: "Assistant", exact: true }).click();
  await page.getByRole("button", { name: "Review proposal", exact: true }).click();
  await expect(page.getByText("LOCAL ENU movement: 500 / 0 / 0 mm", { exact: true })).toBeVisible();
  await page.getByLabel("I reviewed the assumptions, warnings and conceptual scope.").check();
  await page.getByRole("button", { name: "Approve proposal", exact: true }).click();
  const applied = page.waitForResponse(r => /\/build$/.test(r.url()) && r.request().method() === "POST");
  await page.getByRole("button", { name: "Apply approved building patch", exact: true }).click();
  const response = await applied;
  expect(response.ok(), await response.text()).toBeTruthy();
  await expect(page.getByText(/Building patch saved as revision/)).toBeVisible();
  await page.reload();
  await expect(page.getByLabel("Search scene components")).toBeVisible();
  await page.getByLabel("Search scene components").fill("c0-0");
  await page.getByRole("button", { name: "c0-0", exact: true }).click();
  await page.getByRole("tab", { name: "Inspect", exact: true }).click();
  await expect(east).toHaveValue("5.5");
  await expect(page.getByLabel("Component identity")).toContainText("office-01:c0-0");
  await page.getByRole("tab", { name: "History", exact: true }).click();
  await page.getByRole("button", { name: "Compare", exact: true }).click();
  await expect(page.getByText("0 added · 0 removed · 1 modified", { exact: true })).toBeVisible();
  await expect(page.getByText(/Δ East 0.500/)).toBeVisible();
  await page.screenshot({ path: "test-results/building-patch-accepted.png" });
});
