import { expect, test } from "@playwright/test";

const projectId = process.env.PLATFORM_ACCEPTANCE_PROJECT_ID;
test.skip(!projectId, "Requires the offline create_platform_workspace_fixture.py project");

test("review and approve one platform, then edit, save, reload and compare", async ({ page }) => {
  await page.setViewportSize({ width: 1626, height: 982 });
  await page.route("**/api/geocode/map-runtime-config", route => route.fulfill({ json: { cesium_ion_token: null, google_maps_api_key: null } }));
  await page.goto(`/projects/${projectId}/workspace`);
  await expect(page.getByRole("tab", { name: "Assistant", exact: true })).toBeVisible({ timeout: 60000 });
  await page.getByRole("tab", { name: "Assistant", exact: true }).click();
  await page.getByRole("button", { name: "Review proposal", exact: true }).click();
  const review = page.getByLabel("Proposal review");
  const summary = page.getByLabel("Generic 3D design summary");
  await expect(summary).toContainText("INDUSTRIAL MAINTENANCE PLATFORM");
  await expect(summary).toContainText("SLAB: 5 × 3 × 0.2 m");
  await expect(summary).toContainText("approximately 3 m above the local visual reference plane");
  await expect(summary).toContainText("not surveyed ground or engineered absolute elevation");
  await expect(review).toContainText("Loads, foundations, clearances, structural adequacy and code compliance are unverified.");
  await expect(page.getByRole("button", { name: "Approve proposal", exact: true })).toBeDisabled();
  await expect(page.getByRole("button", { name: "Approve & Generate 3D", exact: true })).toHaveCount(0);
  await summary.getByText("INDUSTRIAL MAINTENANCE PLATFORM", { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: "test-results/platform-proposal-review.png" });
  await page.getByRole("checkbox", { name: "I reviewed the assumptions, warnings and conceptual scope." }).check();
  await page.getByRole("button", { name: "Approve proposal", exact: true }).click();
  const built = page.waitForResponse(r => /\/build$/.test(r.url()) && r.request().method() === "POST");
  await page.getByRole("button", { name: "Approve & Generate 3D", exact: true }).click();
  const response = await built;
  expect(response.ok(), await response.text()).toBeTruthy();
  await expect(review.getByRole("status")).toContainText("Generic 3D concept saved as revision");
  await page.reload();
  const selectDeck = async () => {
    await page.getByRole("tab", { name: "Layers", exact: true }).click();
    await page.getByLabel("Search scene components").fill("platform-deck");
    await page.getByRole("button", { name: "platform-deck", exact: true }).click();
    await page.getByRole("tab", { name: "Inspect", exact: true }).click();
  };
  await selectDeck();
  await expect(page.getByLabel("Component identity")).toContainText("industrial-platform-5x3");
  await page.getByRole("button", { name: "Frame selection", exact: true }).click();
  const east = page.getByLabel("Position · metres East", { exact: true });
  await expect(east).toHaveValue("0");
  await east.fill("0.25"); await east.press("Tab");
  const saved = page.waitForResponse(r => /model-revisions$/.test(r.url()) && r.request().method() === "POST");
  await page.getByRole("button", { name: "Save", exact: true }).click();
  const saveResponse = await saved;
  expect(saveResponse.ok(), await saveResponse.text()).toBeTruthy();
  const revision = await saveResponse.json();
  expect(revision.document.components).toHaveLength(9);
  expect(revision.document.origin.elevation_m).toBeNull();
  expect(revision.source).toBe("manual_edit");
  await page.reload(); await selectDeck();
  await expect(east).toHaveValue("0.25");
  await page.getByRole("tab", { name: "History", exact: true }).click();
  await page.getByRole("button", { name: "Compare", exact: true }).click();
  await expect(page.getByText("0 added · 0 removed · 1 modified", { exact: true })).toBeVisible();
  await page.screenshot({ path: "test-results/platform-revision-compare.png" });
  await page.getByRole("button", { name: "Close compare", exact: true }).click();
  await selectDeck();
  await page.getByRole("button", { name: "Frame selection", exact: true }).click();
  await page.waitForTimeout(1800);
  await expect(page.locator(".cesium-widget canvas")).toBeVisible();
  await expect(page.locator(".cesium-widget-errorPanel")).toHaveCount(0);
  await page.screenshot({ path: "test-results/platform-workspace-accepted.png" });
});
