import { expect, test, type Page } from "@playwright/test";

const route = "/projects/999999/workspace?local=1";
const canvasFor = (page: Page) => page.locator('main[aria-label="Layout scene"] canvas').first();

async function place(page: Page, kind: string, x = 0.5, y = 0.6) {
  await page.getByRole("button", { name: new RegExp(`^${kind} \\d`, "i") }).click();
  const canvas = canvasFor(page);
  await expect(canvas).toBeVisible();
  await expect(canvas).toHaveAttribute("data-sandbox-ready", "true");
  await expect(canvas).toHaveAttribute("data-placement", kind);
  const bounds = (await canvas.boundingBox())!;
  await page.mouse.move(bounds.x + bounds.width * x, bounds.y + bounds.height * y);
  await page.mouse.click(bounds.x + bounds.width * x, bounds.y + bounds.height * y);
}

test("sandbox placement, edits, undo, save, map, and backup round trip", async ({ page }) => {
  const projectRequests: string[] = [];
  const errors: string[] = [];
  page.on("request", (request) => { if (/\/api\/projects\/999999/.test(request.url())) projectRequests.push(request.url()); });
  page.on("pageerror", (error) => errors.push(error.message));
  await page.route("**/api/geocode/map-runtime-config", route => route.fulfill({ json: { cesium_ion_token: null, google_maps_api_key: null } }));
  await page.goto(route);
  await expect(page.getByText("Build your first layout")).toBeVisible();
  await expect(page.getByRole("button", { name: /^Generate/ })).toHaveCount(0);
  await place(page, "building");
  await expect(page.getByLabel("Component name")).toHaveValue("building 1");
  await page.getByLabel("Dimensions (m) Width", { exact: true }).fill("14");
  await page.getByLabel("Dimensions (m) Width", { exact: true }).press("Enter");
  await expect(page.getByLabel("Dimensions (m) Width", { exact: true })).toHaveValue("14");
  await place(page, "road", 0.68, 0.72);
  await expect(page.getByLabel("Component name")).toHaveValue("road 2");
  await page.getByRole("button", { name: "Duplicate", exact: true }).click();
  await expect(page.getByRole("button", { name: "road 2 copy", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByRole("button", { name: "road 2 copy", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "building 1", exact: true }).click();
  await page.getByRole("button", { name: "Move", exact: true }).click();
  await page.screenshot({ path: "test-results/sandbox-grid.png" });
  await page.getByRole("button", { name: "Fit all", exact: true }).click();
  await expect(page.getByRole("status")).toHaveText("Saved locally");
  await page.reload();
  await expect(page.getByRole("button", { name: "building 1", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "road 2", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Undo", exact: true })).toBeDisabled();
  // With no Ion token, the actual provider is Cesium's bundled world imagery.
  const basemapTile = page.waitForResponse((response) => /\/cesium\/Assets\/Textures\/NaturalEarthII\/.*\.(?:jpg|png)/i.test(response.url()) && response.status() === 200);
  await page.getByRole("button", { name: "Map", exact: true }).click();
  await basemapTile;
  await expect(page.locator(".cesium-widget canvas")).toBeVisible({ timeout: 60000 });
  await expect(page.locator(".cesium-widget canvas")).toHaveAttribute("data-sandbox-ready", "true", { timeout: 60000 });
  await page.getByRole("button", { name: "building 1", exact: true }).click();
  await expect(page.getByLabel("Dimensions (m) Width", { exact: true })).toHaveValue("14");
  await expect(page.locator(".cesium-widget canvas")).toHaveAttribute("data-sandbox-ready", "true", { timeout: 60000 });
  await page.getByRole("button", { name: /^Geographic origin/ }).click();
  await page.getByLabel("Latitude", { exact: true }).fill("13.01");
  await page.getByLabel("Latitude", { exact: true }).press("Enter");
  await expect(page.getByText(/^Origin 13\.010000/)).toBeVisible();
  await expect(page.locator(".cesium-widget canvas")).toHaveAttribute("data-sandbox-ready", "true", { timeout: 60000 });
  await page.screenshot({ path: "test-results/sandbox-map.png" });
  await page.getByRole("button", { name: "Grid", exact: true }).click();
  await expect(canvasFor(page)).toBeVisible();
  const downloaded = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download backup", exact: true }).click();
  const backup = await downloaded;
  const backupPath = (await backup.path())!;
  await page.getByRole("button", { name: "New layout", exact: true }).click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("button", { name: "Replace layout", exact: true }).click();
  await expect(page.getByText("Build your first layout")).toBeVisible();
  await page.getByLabel("Sandbox backup file").setInputFiles(backupPath);
  await expect(page.getByRole("dialog")).toBeVisible();
  await page.getByRole("button", { name: "Replace layout", exact: true }).click();
  await expect(page.getByRole("button", { name: "building 1", exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "road 2", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Save locally", exact: true }).last().click();
  await expect(page.getByRole("status")).toHaveText("Saved locally");
  expect(projectRequests).toEqual([]);
  expect(errors).toEqual([]);
});

test("grid handles commit once, Escape cancels, and shortcuts ignore inputs", async ({ page }) => {
  await page.goto(route);
  await place(page, "building");
  const east = page.getByLabel("Position (m) East", { exact: true });
  const north = page.getByLabel("Position (m) North", { exact: true });
  const initial = [await east.inputValue(), await north.inputValue()];
  await page.getByRole("button", { name: "Move", exact: true }).click();
  await expect(canvasFor(page)).toHaveAttribute("data-sandbox-ready", "true");
  await page.screenshot({ path: "test-results/sandbox-before-drag.png" });
  const bounds = (await canvasFor(page).boundingBox())!;
  const x = bounds.x + bounds.width * 0.5 + 35;
  const y = bounds.y + bounds.height * 0.6 + 2;
  await page.mouse.move(x, y);
  await page.mouse.down();
  await page.mouse.move(x + 55, y + 25, { steps: 12 });
  await page.mouse.up();
  await expect(east).not.toHaveValue(initial[0]);
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(east).toHaveValue(initial[0]);
  await expect(north).toHaveValue(initial[1]);
  await page.getByRole("button", { name: "building 1", exact: true }).click();
  await page.getByRole("button", { name: "Move", exact: true }).click();
  await expect(canvasFor(page)).toHaveAttribute("data-sandbox-ready", "true");
  await page.mouse.move(x, y);
  await page.mouse.down();
  await page.mouse.move(x + 70, y + 30, { steps: 12 });
  await page.keyboard.press("Escape");
  await page.mouse.up();
  await expect(east).toHaveValue(initial[0]);
  await expect(north).toHaveValue(initial[1]);
  await page.getByLabel("Component name").fill("Building g r s");
  await expect(page.getByRole("button", { name: "Building g r s", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByLabel("Component name")).toHaveValue("building 1");
  await page.getByRole("button", { name: "Undo", exact: true }).click();
  await expect(page.getByText("Build your first layout")).toBeVisible();
});
